### ISSUE TITLE
jstorm rebalance 无法正常使用？

### ISSUE THREAD

**Issue by qzhJie** [alibaba/jstorm#497]
我代码设置的spout的parallelism hint 是 5 ，database的parallelism hint 是10，然后我使用`jstorm rebalance -r SpiderTopology  conf.yaml` 来降低并行度却不行。增加并行度却可以
conf.yaml 是：
```
topology.workers: 2
topology.acker.executors: 2

topology.spout.parallelism:
  spout: 1
topology.bolt.parallelism:
  database: 2
```
